#!/bin/bash

DATA_DIR="${TRIM_DATA_SHARE_PATHS%%:*}"
LOG_FILE="${DATA_DIR}/run.log"
PID_FILE="${TRIM_PKGVAR}/app.pid"

DP_STORAGE_LOCAL_PATH="${DATA_DIR}/data"

# write the command to start your program here 
CMD="${TRIM_APPDEST}/server/dpanel \
      -e APP_SERVER_PORT=${DP_APP_SERVER_PORT} \
      -e STORAGE_LOCAL_PATH=${DP_STORAGE_LOCAL_PATH}"

log_msg() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> ${LOG_FILE}
}

start_process() {
    log_msg "============== Debug Info =============="
    log_msg "[Sys] ID: ${TRIM_SYS_MACHINE_ID:--}"
    log_msg "[Sys] 用户: ${TRIM_RUN_USERNAME:--}:${TRIM_RUN_GROUPNAME:--} (${TRIM_RUN_UID:--}:${TRIM_RUN_GID:--})"
    log_msg "[Sys] 版本: ${TRIM_SYS_VERSION:--}"
    log_msg "[Sys] 架构: ${TRIM_SYS_ARCH:--}"
    log_msg "[Sys] 内核: ${TRIM_KERNEL_VERSION:--}"
    log_msg "[Sys] 语言: ${TRIM_SYS_LANGUAGE:--}"
    log_msg "[Sys] 动态数据: ${TRIM_PKGVAR:--}"
    log_msg "[Sys] 临时文件: ${TRIM_PKGTMP:--}"
    log_msg "[Sys] 用户数据: ${TRIM_PKGHOME:--}"
    log_msg "[Sys] 元数据: ${TRIM_PKGMETA:--}"
    log_msg "[Sys] 日志文件: ${TRIM_TEMP_LOGFILE:--}"
    log_msg "[Sys] 升级临时: ${TRIM_TEMP_UPGRADE_FOLDER:--}"
    log_msg "[Sys] 安装临时: ${TRIM_PKGINST_TEMP_DIR:--}"
    log_msg "[Sys] FPK解压: ${TRIM_TEMP_TPKFILE:--}"
    log_msg "===================================="
    log_msg "[App] 用户: ${TRIM_USERNAME:--}:${TRIM_GROUPNAME:--} (${TRIM_UID:--}:${TRIM_GID:--})"
    log_msg "[App] 名称: ${TRIM_APPNAME:--}"
    log_msg "[App] 版本: ${TRIM_APPVER:--}"
    log_msg "[App] 状态: ${TRIM_APP_STATUS:--}"
    log_msg "[App] 端口: ${TRIM_SERVICE_PORT:--}"
    log_msg "[App] 工作目录: ${TRIM_APPDEST:--}"
    log_msg "[App] 配置文件: ${TRIM_PKGETC:--}"
    log_msg "[App] 存储空间: ${TRIM_APPDEST_VOL:--}"
    log_msg "[App] 共享目录: ${TRIM_DATA_SHARE_PATHS:--}"

    if status; then
        return 0
    fi

    log_msg "Starting process ..."
    # run cmd to start process
    export PATH="/usr/local/bin:/usr/bin:/bin:$PATH"
    bash -c "${CMD} server:start" >> ${LOG_FILE} 2>&1 &
    # write pid to pidfile
    PID=$!
    printf "%s" "$PID" > ${PID_FILE}
    log_msg "CMD = ${CMD}"
    log_msg "pid = $PID"

    if [ -n "${DP_INIT_USERNAME}" ] && [ -n "${DP_INIT_PASSWORD}" ]; then
        log_msg "Init user ... ${DP_INIT_USERNAME}/${DP_INIT_PASSWORD}"
        # 最多等待 30 秒，查找是否有关键字
        MAX_RETRIES=30
        COUNT=0
        while ! grep -q "provider load" "${LOG_FILE}" && [ $COUNT -lt $MAX_RETRIES ]; do
            sleep 1
            ((COUNT++))
        done
        bash -c "${CMD} user:reset --username ${DP_INIT_USERNAME} --password ${DP_INIT_PASSWORD}" >> ${LOG_FILE} 2>&1 &
    fi

    return 0
}

stop_process() {
    log_msg "Stopping process ..."

    if [ -r "${PID_FILE}" ]; then
        pid=$(head -n 1 "${PID_FILE}" | tr -d '[:space:]')
        
        log_msg "pid=${pid}"
        if ! check_process "${pid}"; then
            # process not exist, delete pidfile
            rm -f "${PID_FILE}"
            log_msg "remove pid file 1"
            return
        fi

        log_msg "send TERM signal to PID:${pid}..."
        kill -TERM ${pid} >> ${LOG_FILE} 2>&1

        local count=0
        while check_process "${pid}" && [ $count -lt 10 ]; do
            sleep 1
            count=$((count + 1))
            log_msg "waiting process terminal... (${count}s/10s)"
        done

        if check_process "${pid}"; then
            log_msg "send KILL signal to PID:${pid}..."
            kill -KILL "${pid}"
            sleep 1
            rm -f "${PID_FILE}"
        else
            log_msg "process killed... "
        fi
    fi

    return 0
}

check_process() {
    local pid=$1
    if kill -0 "${pid}" 2>/dev/null; then
        return 0  # process exist
    else
        return 1  # process not exist
    fi
}

status() {
    if [ -f "${PID_FILE}" ]; then
        pid=$(head -n 1 "${PID_FILE}" | tr -d '[:space:]')
        if check_process "${pid}"; then
            return 0
        else
            # Process is not running but pidfile exists - clean it up
            rm -f "${PID_FILE}"
        fi    
    fi

    return 1
}

case $1 in
start)
    # run start command. exit 0 if success, exit 1 if failed
    start_process
    ;;
stop)
    # run stop command. exit 0 if success, exit 1 if failed
    stop_process
    ;;
status)
    # check application status command. exit 0 if running, exit 3 if not running
    if status; then 
        exit 0
    else 
        exit 3
    fi
    ;;
*)
    exit 1
    ;;
esac